"use strict";(self.webpackChunkmy_website=self.webpackChunkmy_website||[]).push([[904],{60194:function(d,n,t){t.r(n),t.d(n,{demos:function(){return e}});var _=t(38497),o=t(19471),e={}},70827:function(d,n,t){t.r(n),t.d(n,{demos:function(){return e}});var _=t(38497),o=t(26496),e={}},25164:function(d,n,t){t.r(n),t.d(n,{demos:function(){return e}});var _=t(38497),o=t(84930),e={}},88626:function(d,n,t){t.r(n),t.d(n,{demos:function(){return e}});var _=t(38497),o=t(1159),e={}},57756:function(d,n,t){t.r(n),t.d(n,{demos:function(){return e}});var _=t(38497),o=t(37619),e={}},72876:function(d,n,t){t.r(n),t.d(n,{demos:function(){return e}});var _=t(38497),o=t(50012),e={}},70382:function(d,n,t){t.r(n),t.d(n,{demos:function(){return e}});var _=t(38497),o=t(91896),e={}},68849:function(d,n,t){t.r(n),t.d(n,{demos:function(){return e}});var _=t(38497),o=t(74579),e={}},15799:function(d,n,t){t.r(n),t.d(n,{demos:function(){return e}});var _=t(38497),o=t(98107),e={}},59719:function(d,n,t){t.r(n),t.d(n,{demos:function(){return e}});var _=t(38497),o=t(30619),e={}},1968:function(d,n,t){t.r(n),t.d(n,{demos:function(){return e}});var _=t(38497),o=t(44772),e={}},7157:function(d,n,t){t.r(n),t.d(n,{demos:function(){return e}});var _=t(38497),o=t(60781),e={}},34700:function(d,n,t){t.r(n),t.d(n,{demos:function(){return e}});var _=t(38497),o=t(90414),e={}},29640:function(d,n,t){t.r(n),t.d(n,{demos:function(){return e}});var _=t(38497),o=t(42414),e={}},60245:function(d,n,t){t.r(n),t.d(n,{texts:function(){return o}});var _=t(19471);const o=[{value:"\u6211\u7684\u540D\u5B57",paraId:0}]},23581:function(d,n,t){t.r(n),t.d(n,{texts:function(){return o}});var _=t(26496);const o=[{value:"```jsconsole.log('hello world')``````jsconsol",paraId:0}]},93047:function(d,n,t){t.r(n),t.d(n,{texts:function(){return o}});var _=t(84930);const o=[{value:"321",paraId:0}]},86866:function(d,n,t){t.r(n),t.d(n,{texts:function(){return o}});var _=t(1159);const o=[]},47578:function(d,n,t){t.r(n),t.d(n,{texts:function(){return o}});var _=t(37619);const o=[]},34857:function(d,n,t){t.r(n),t.d(n,{texts:function(){return o}});var _=t(50012);const o=[]},99865:function(d,n,t){t.r(n),t.d(n,{texts:function(){return o}});var _=t(91896);const o=[]},7751:function(d,n,t){t.r(n),t.d(n,{texts:function(){return o}});var _=t(74579);const o=[{value:"\u6CE8\u610F\uFF1AWindows\u7CFB\u7EDF\u4E0B\u662F.ini\u6587\u4EF6\uFF0CLinux\u7CFB\u7EDF\u4E0B\u662F.cof\u6587\u4EF6",paraId:0,tocIndex:2},{value:"\u4E3B\u8981\u4FEE\u6539\u7684\u914D\u7F6E\u662F[client]\u4E0B\u7684port\uFF1B[mysqld]\u4E0B\u7684port\u3001basedir\u3001datadir",paraId:1,tocIndex:2},{value:"\u6CE8\u610F\uFF1A\u8FD9\u91CC\u53EA\u662F\u90E8\u5206\u7684\u914D\u7F6E\uFF0C\u66F4\u591A\u7684\u914D\u7F6E\u8BF7\u67E5\u770B\u6587\u6863\uFF0C\u6216\u8005AI\u641C\u7D22",paraId:2,tocIndex:2},{value:`# For advice on how to change settings please see
# http://dev.mysql.com/doc/refman/5.6/en/server-configuration-defaults.html
# *** DO NOT EDIT THIS FILE. It's a template which will be copied to the
# *** default location during install, and will be replaced if you
# *** upgrade to a newer version of MySQL.
[client]
port=3309

[mysql]

#log-error=d:/mysql_log_err.txt
[mysqld]
port=3309
basedir=S:\\MySQL\\mysql-9.0.1-winx64
datadir=S:\\MySQL\\mysql-9.0.1-winx64\\Data
character-set-server=utf8mb4
#\u8FDE\u63A5\u7A7A\u95F2\u65F6\u95F4 30\u5206
wait_timeout=1800
#\u6700\u5927\u8FDE\u63A5\u6570
max_connections=500

#\u5F00\u542F\u4E8B\u4EF6 
event_scheduler = 1
#\u5F00\u542F\u6162\u67E5\u8BE2\u65E5\u5FD7
slow_query_log = ON
#slow_query_log_file = ../slow_query.log
long_query_time = 5
#\u7981\u7528\u57DF\u540D\u89E3\u6790
#skip-name-resolve
#\u7981\u7528TCP/IP\u8FDC\u7A0B\u8FDE\u63A5
#skip-networking
#key_buffer_size=16M
#innodb_buffer_pool_size=4G
#innodb_additional_mem_pool_size=20M
#innodb_log_buffer_size=20M
#query_cache_size=40M
#read_buffer_size=4M
#sort_buffer_size=4M
#read_rnd_buffer_size=8M
#tmp_table_size=16M
#thread_cache_size=16
# Remove leading # and set to the amount of RAM for the most important data
# cache in MySQL. Start at 70% of total RAM for dedicated server, else 10%.
# innodb_buffer_pool_size = 128M

# Remove leading # to turn on a very important data integrity option: logging
# changes to the binary log between backups.
log_bin="k_logbin"

# These are commonly set, remove the # and set as required.
# basedir = .....
# datadir = .....
# port = .....
# server_id = .....


# Remove leading # to set options mainly useful for reporting servers.
# The server defaults are faster for transactions and fast SELECTs.
# Adjust sizes as needed, experiment to find the optimal values.
# join_buffer_size = 128M
# sort_buffer_size = 2M
# read_rnd_buffer_size = 2M 

sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
log-bin-trust-function-creators=1

`,paraId:3,tocIndex:2},{value:`\u4F7F\u7528\u7BA1\u7406\u5458\u6A21\u5F0F\u8FDB\u5165MySQL\u7684bin\u76EE\u5F55\u4E0B
`,paraId:4,tocIndex:3},{value:`\u4F7F\u7528mysqld\u6267\u884C--initialize --console\u547D\u4EE4 \uFF0C\u6CE8\u610F\u4E0D\u540C\u7684\u547D\u4EE4\u884C\uFF0C\u8C03\u7528mysqld\u7684\u683C\u5F0F\u4E0D\u4E00\u6837\uFF0C\u6211\u8FD9\u91CC\u662F.\\mysqld.exe --initialize --console
`,paraId:5,tocIndex:3},{value:"\u8BB0\u4F4F\u8FD9\u4E2A\u4E34\u65F6\u5BC6\u7801",paraId:5,tocIndex:3},{value:"\u6CE8\u610F\uFF1A\u8FD9\u91CC\u9700\u8981\u4F7F\u7528\u7BA1\u7406\u5458\u6A21\u5F0F",paraId:6,tocIndex:4},{value:`sc delete MySQL90
mysqld --install MySQL90 --defaults-file="S:\\MySQL\\mysql-9.0.1-winx64\\my.ini"
`,paraId:7,tocIndex:4},{value:"\u6253\u5F00\u670D\u52A1\u754C\u9762\u542F\u52A8\u670D\u52A1\u5373\u53EF",paraId:8,tocIndex:4},{value:"\u8FD9\u91CC\u9700\u8981\u4F7F\u7528",paraId:9,tocIndex:5},{value:"\u6B65\u9AA4\u4E09",paraId:9,tocIndex:5},{value:" \u83B7\u53D6\u7684\u4E34\u65F6\u5BC6\u7801",paraId:9,tocIndex:5},{value:"\u70B9\u51FB\u786E\u5B9A\u540E\uFF0C\u53CC\u51FB\u8FDE\u63A5\u540D\u79F0\uFF0C\u4F1A\u63D0\u793A\u8BA9\u8F93\u5165\u65B0\u5BC6\u7801",paraId:10,tocIndex:5}]},45074:function(d,n,t){t.r(n),t.d(n,{texts:function(){return o}});var _=t(98107);const o=[]},96088:function(d,n,t){t.r(n),t.d(n,{texts:function(){return o}});var _=t(30619);const o=[]},36655:function(d,n,t){t.r(n),t.d(n,{texts:function(){return o}});var _=t(44772);const o=[{value:"\u751F\u6210\u6D4B\u8BD5\u5185\u5BB9",paraId:0,tocIndex:0}]},57147:function(d,n,t){t.r(n),t.d(n,{texts:function(){return o}});var _=t(60781);const o=[{value:"nav\u7684title\uFF1A\u5BFC\u822A\u680F\u7684\u6807\u9898",paraId:0,tocIndex:2},{value:"group\u7684title\uFF1A\u5206\u7EC4\u7684\u6807\u9898",paraId:0,tocIndex:2},{value:"title\uFF1A\u9875\u9762\u7684\u6807\u9898",paraId:0,tocIndex:2},{value:"docs\u662F\u6587\u6863\u7684\u6839\u76EE\u5F55\uFF0C\u5728\u6839\u76EE\u5F55\u4E0B\u5206\u4E3A\uFF0C\u4EE5md\u6587\u4EF6\u65B9\u5F0F\u6E32\u67D3nav\u548C\u4EE5\u6587\u4EF6\u5939\u65B9\u5F0F\u6E32\u67D3nav\uFF1B\u56E0\u6B64\uFF0C\u5728\u6839\u76EE\u5F55\u4E0B\u7684md\u6587\u4EF6\uFF0C\u4F1A\u88AB\u6E32\u67D3\u4E3Anav\uFF0C\u800C\u5728\u6839\u76EE\u5F55\u4E0B\u7684\u6587\u4EF6\u5939\uFF0C\u4F1A\u88AB\u5F53\u6210\u4E00\u7EC4\uFF0C\u4E00\u7EC4\u4E2D\u53EA\u6709\u4E00\u4E2Amd\u6587\u4EF6\uFF0C\u4F1A\u88AB\u6E32\u67D3\u4E3Anav\u3002",paraId:1,tocIndex:3}]},92412:function(d,n,t){t.r(n),t.d(n,{texts:function(){return o}});var _=t(90414);const o=[{value:"test\u6570\u636E",paraId:0,tocIndex:0}]},55730:function(d,n,t){t.r(n),t.d(n,{texts:function(){return o}});var _=t(42414);const o=[]}}]);
